### ISSUE TITLE
Data Storage: SQLite or alternative

### ISSUE THREAD

**Issue by kyr0** [rage8885/OpenSC2K#11]
...if you can have localForage with localStorage? Removing SQLite would also eliminate the native dependency which in turn will fix a bunch of issues here (cross-platform native compile issues).

LocalStorage in electron is limited to 10MB in size. But for game data it should never exceed that limit, no?

The tile/city data could be exported into JSON files and thus be lazy-loaded. Wouldn't imply a problematic performance impact, but simplify the architecture a lot.

**Comment by rage8885** [comment]
I started off with LocalStorage / JSON initially, but with some of the changes to how the cities were imported a SQL-like back end made sense. I'd like to remove the native dependency altogether however, that seems to be where most of the cross platform issues are popping up.

IndexedDB with a more "user friendly" interface is what I'm leaning towards right now, something like Dexie.js for example.

**Comment by rage8885** [comment]
SQLite dependency has been removed entirely
