### ISSUE TITLE
webpack it!

### ISSUE THREAD

**Issue by TheLarkInn** [rage8885/OpenSC2K#17]
Hey!!! Sean from the webpack team! Would you take a PR if provided to bundle the assets on both main and renderer portions of this application?!

Pros: startup and render performance could be significantly faster!

Cons: have a build step?

I've been looking for a great case study for electron performance and app migration and I think this would be a great one.

Thanks!
Sean - webpack team

**Comment by mozts2005** [comment]
I would be willing to setup a CI build in appveyor for your webpack build step.

**Comment by rage8885** [comment]
Sure

**Comment by TheLarkInn** [comment]
In hopes of not biting off more then I can chew, if it would be beneficial to allow a broader collaboration for this, and given a PR would be acceptable, I can create (or update this issue) to include a spec like set of requirements and isolated tasks for contributors to tackle. That way this work isn't just hung up by myself (if it turns out to be a larger task).

**Comment by cursorial** [comment]
I'd be interested in helping out with this, I've been looking for a reason
to learn about how webpack is used but haven't found the right project so
it'd be a great learning experience.

**Comment by whphhg** [comment]
Can you please explain (or if you have any links handy) to the layman why using `webpack` with `electron` and serving the code through a server instead of consuming it directly, would be faster?

**Comment by cursorial** [comment]
@whphhg I didn't think that webpack required you to serve it through a server? It can be used to just compress the code into single files can't it? Maybe I'm misunderstanding what it does?

**Comment by whphhg** [comment]
@cursorial you are correct, I have misunderstood how it's used all this time. The server is only used for HMR and in production it loads the local entry point.

I've found these resources to be useful:
- https://webpack.electron.build
- https://github.com/electron-userland/electron-webpack-quick-start

**Comment by DevNebulae** [comment]
Did somebody pick this up already? I have some spare time tonight / this weekend and I want to look into this.

**Comment by cursorial** [comment]
I haven't touched it yet myself, I'd just go for any issues that @rage8885
hasn't assigned to himself unless someone has commented that they're
working on it.

**Comment by TheLarkInn** [comment]
Hi finally have a bit of time to split some things up here! I'm going to pull the code down first and do a little assessment before getting started.

**Comment by DevNebulae** [comment]
@TheLarkInn I discovered an issue while trying to implement this feature, check #32 to see the issue I ran into, but it is being worked on.

**Comment by rage8885** [comment]
The re-write is now using webpack/eslint, closing this one.
