### ISSUE TITLE
OSX?

### ISSUE THREAD

**Issue by theronic** [rage8885/OpenSC2K#18]
Will this run on OSX? Haven't tried yet, but I see Linux and Windows instructions on README

**Comment by THEozmic** [comment]
@theronic It does run on OSX

**Comment by cursorial** [comment]
Please read the README. It's there for a reason.

**Comment by ZYMoridae** [comment]
@theronic follow the README and it works

**Comment by rage8885** [comment]
#22 should help with this, thanks @cursorial
