### ISSUE TITLE
Error at launch (in web console) (Using windows)

### ISSUE THREAD

**Issue by vasilvestre** [rage8885/OpenSC2K#19]
Here the error :
`Uncaught Error: Une routine d'initialisation d'une bibliothèque de liens dynamiques (DLL) a échoué.
\\?\C:\OpenSC2K\node_modules\better-sqlite3\build\Release\better_sqlite3.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (C:\OpenSC2K\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\OpenSC2K\node_modules\better-sqlite3\lib\database.js:4:40)`

**Comment by cursorial** [comment]
https://github.com/rage8885/OpenSC2K/issues/14

**Comment by cursorial** [comment]
Please read the README.

Its there for a reason.

**Comment by vasilvestre** [comment]
Well I did. And it doesn't work...

**Comment by cursorial** [comment]
See issue https://github.com/rage8885/OpenSC2K/issues/4 for solution.

**Comment by cursorial** [comment]
What output do you get after running Step 5. Can you try removing the OpenSC2K directory, cloning again and then running the commands and posting the output of each? Maybe something's going wrong during installation that we haven't seen yet.

**Comment by vasilvestre** [comment]
Full log here : 
`C:\Users\vsilvestre
λ git clone https://github.com/rage8885/OpenSC2K.git
Cloning into 'OpenSC2K'...
remote: Counting objects: 2137, done.
remote: Compressing objects: 100% (2033/2033), done.
remote: Total 2137 (delta 112), reused 2112 (delta 99), pack-reused 0
Receiving objects: 100% (2137/2137), 24.63 MiB | 5.65 MiB/s, done.
Resolving deltas: 100% (112/112), done.
Checking out files: 100% (3812/3812), done.

C:\Users\vsilvestre
λ cd OpenSC2K

C:\Users\vsilvestre\OpenSC2K (master) (OpenSC2K@0.0.1)
λ npm install --global --production windows-build-tools

> windows-build-tools@1.4.2 postinstall C:\Users\vsilvestre\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./lib/index.js

Downloading BuildTools_Full.exe
Downloading python-2.7.14.amd64.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.14.amd64.msi. Saved to C:\Users\vsilvestre\.windows-build-tools\python-2.7.14.amd64.msi.
Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
Waiting for installers... \Successfully installed Visual Studio Build Tools.
Successfully installed Python 2.7
+ windows-build-tools@1.4.2
updated 1 package in 39.284s

C:\Users\vsilvestre\OpenSC2K (master) (OpenSC2K@0.0.1)
λ npm install

> integer@1.0.3 install C:\Users\vsilvestre\OpenSC2K\node_modules\integer
> node tools/install


C:\Users\vsilvestre\OpenSC2K\node_modules\integer>if not defined npm_config_node_gyp (node "C:\Users\vsilvestre\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\vsilvestre\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
  integer.cpp
  win_delay_load_hook.cc
..\src\integer.cpp(370): warning C4804: '-': unsafe use of type 'bool' in operation [C:\Users\vsilvestre\OpenSC2K\node_modules\integer\build\integer.vcxproj]
..\src\integer.cpp(376): warning C4244: '=': conversion from 'uint64_t' to 'unsigned char', possible loss of data [C:\Users\vsilvestre\OpenSC2K\node_modules\integer\build\integer.vcxproj]
     Creating library C:\Users\vsilvestre\OpenSC2K\node_modules\integer\build\Release\integer.lib and object C:\Users\vsilvestre\OpenSC2K\node_modules\integer\build\Release\integer.exp
  Generating code
  Finished generating code
  integer.vcxproj -> C:\Users\vsilvestre\OpenSC2K\node_modules\integer\build\Release\\integer.node
  integer.vcxproj -> C:\Users\vsilvestre\OpenSC2K\node_modules\integer\build\Release\integer.pdb (Full PDB)

> better-sqlite3@4.1.0 install C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3
> node deps/install

==> cwd: C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3
==> C:\Users\vsilvestre\OpenSC2K\node_modules\lzz-gyp\lzz-compiled\windows.exe -hx hpp -sx cpp -k BETTER_SQLITE3 -d -hl -sl -e ./src/better_sqlite3.lzz
==> cwd: C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3
==> node-gyp rebuild

C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3>if not defined npm_config_node_gyp (node "C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\vsilvestre\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
Génération des projets individuellement dans cette solution. Pour activer la génération en parallèle, ajoutez le commutateur "/m".
  unpack_sqlite_dep
  sqlite3.c
  win_delay_load_hook.cc
  sqlite3.vcxproj -> C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3\build\Release\\sqlite3.lib
  better_sqlite3.cpp
  win_delay_load_hook.cc
     Creating library C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3\build\Release\better_sqlite3.lib and object C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3\build\Release\better_sqli
  te3.exp
  Generating code
  Finished generating code
  better_sqlite3.vcxproj -> C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3\build\Release\\better_sqlite3.node
  better_sqlite3.vcxproj -> C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3\build\Release\better_sqlite3.pdb (Full PDB)
  test_extension.c
  win_delay_load_hook.cc
  Generating code
  Finished generating code
  test_extension.vcxproj -> C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3\build\Release\\test_extension.node
  test_extension.vcxproj -> C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3\build\Release\test_extension.pdb (Full PDB)

> electron@1.8.2-beta.5 postinstall C:\Users\vsilvestre\OpenSC2K\node_modules\electron
> node install.js

added 220 packages in 47.376s

C:\Users\vsilvestre\OpenSC2K (master) (OpenSC2K@0.0.1)
λ npm start

> OpenSC2K@0.0.1 start C:\Users\vsilvestre\OpenSC2K
> electron .

Uncaught Error: Une routine dinitialisation dune bibliothèque de liens dynamiques (DLL) a échoué.
\\?\C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3\build\Release\better_sqlite3.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at bindings (C:\Users\vsilvestre\OpenSC2K\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\Users\vsilvestre\OpenSC2K\node_modules\better-sqlite3\lib\database.js:4:40)
`

**Comment by cursorial** [comment]
It looks like you missed a step between npm install and npm start.

    node_modules/.bin/electron-rebuild -f -w better-sqlite3

As far as I'm aware the node version used by the author is 5.7, maybe try updating node if that doesn't work?

**Comment by vasilvestre** [comment]
`C:\Users\vsilvestre\OpenSC2K (master) (OpenSC2K@0.0.1)
λ node_modules/.bin/electron-rebuild -f -w better-sqlite3
'node_modules' n’est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.`

**Comment by cursorial** [comment]
Does the node_modules/.bin directory exist?

Try 

    node_modules\.bin\electron-rebuild -f -w better-sqlite3

It looks like you're having a syntax error when you type it into CMD. If the above command doesn't work try using Git Bash (should have been installed when you installed git on your computer, it's a standalone executable that gives you a bash prompt rather than a windows prompt)

**Comment by vasilvestre** [comment]
node_modules exist, and I use Cmder with git bash

**Comment by cursorial** [comment]
Git bash wouldn't respond with that type of error - it would simply say 

    $ node_modules
    bash: node_modules: command not found

You aren't using the right type of slashes, you are using forward slash, not back slash (windows FS uses back slashes). The prompt thinks you are trying to execute something called node_modules, try replacing all forward slashes with back slashes.

**Comment by cdubz** [comment]
Note the directory separator with this command. On Windows it needs to be as @cursorial provides it above (`\`). Otherwise you’ll get the “node_modules unknown” error because Windows thinks you are asking for an executable as opposed to a folder.

I was trying not to be too verbose with the install instructions in the README, but perhaps there should be a separate list of steps for Windows to avoid this confusion...

**Comment by vasilvestre** [comment]
Look at my pastebin, I use backslash..

**Comment by cdubz** [comment]
This line makes it sound like the Windows build tools are not being found:

`MSBUILD : error MSB4132: La version des outils "2.0" n'est pas reconnue. Les versions disponibles sont "14.0", "4.0".`

Perhaps wipe out `node_modules` and run through the install steps again? I think I had a similar issue when I ran a failed `npm install` the very first time.

**Comment by vasilvestre** [comment]
https://pastebin.com/w08J83WF Again the error..

**Comment by vasilvestre** [comment]
I FIXED IT !
Thanks to https://github.com/chjj/pty.js/issues/60

`open up a new cmd as administrator and run this command:
npm install --global --production windows-build-tools
then
npm config set msvs_version 2015 --global
close all instances of shell/cmd, reopen a cmd (regular this time, non-administrator) return to your directory where you are trying to run npm install and run it again`

I also installed https://www.microsoft.com/en-us/download/details.aspx?id=40760 but I don't think it helped.
Add to README that windows users (at least) need to restart a cmb without admin to rebuild :)

**Comment by cursorial** [comment]
I was just about to comment with that command - well done.

This should be added to the README after where windows-build-tools is installed

- Run this
    npm config set msvs_version 2015 --global
- Close all instances of shell/cmd, reopen a CMD (non-admin), return to the OpenSC2K directory and run the following
    npm install

**Comment by cdubz** [comment]
Curious. I wonder why I haven't had that same requirement for the two Windows installs I have done...

**Comment by cursorial** [comment]
https://github.com/rage8885/OpenSC2K/pull/22

**Comment by cursorial** [comment]
@cdubz Maybe your node installation was already configured to use that version of msvs - hard to tell.

**Comment by cursorial** [comment]
@vasilvestre @rage8885 This issue can be closed now.
