### ISSUE TITLE
electron-rebuild: The system cannot find the path specified. (Windows)

### ISSUE THREAD

**Issue by jonathanlinat** [rage8885/OpenSC2K#23]
I did exactly what it's described here:

1. `git clone https://github.com/rage8885/OpenSC2K` or download this repository
2. `cd OpenSC2K`
3. **Windows**: `npm install --global --production windows-build-tools` (as admin) installs Windows specific prerequisites
4. `npm install` downloads and installs the dependancies
5. **Windows/Linux**: `node_modules/.bin/electron-rebuild -f -w better-sqlite3` rebuilds Electron with better-sqlite3 bindings
6. `npm start` to run

But when I execute `/node_modules/.bin/electron-rebuild -f -w better-sqlite3` on Windows 10 into a non-admin **cmd** (cmder), I have this result: `The system cannot find the path specified.`.

![image](https://user-images.githubusercontent.com/14064112/35930199-0f6dafaa-0c10-11e8-8216-864f32a1d44e.png)

**Comment by cursorial** [comment]
You're in the wrong directory.

    cd C:\Users\jonathan.linat\GitHub\OpenSC2K
    node_modules/.bin/electron-rebuild -f -w better-sqlite3

**Comment by jonathanlinat** [comment]
![image](https://user-images.githubusercontent.com/14064112/35930300-51cb7a12-0c10-11e8-9709-81b232860217.png)

**Comment by cursorial** [comment]
My bad, I used forward slashes, change all to backslash because Windows.

    node_modules\.bin\electron-rebuild -f -w better-sqlite3

**Comment by jonathanlinat** [comment]
![image](https://user-images.githubusercontent.com/14064112/35930403-8e5514d4-0c10-11e8-8e92-77d1fbb9d0e8.png)
