### ISSUE TITLE
mac sierra cannot start because of better-sqlite3 install warning

### ISSUE THREAD

**Issue by xiongjy2104** [rage8885/OpenSC2K#25]
> OpenSC2K@0.0.1 start /Users/xxxxx/workspace/OpenSC2K
> electron .

2018-02-08 20:47:15.924 Electron Helper[24154:5630488] Couldn't set selectedTextBackgroundColor from default ()

SOLINK_MODULE(target) Release/better_sqlite3.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]
  CC(target) Release/obj.target/test_extension/deps/test_extension.o
  SOLINK_MODULE(target) Release/test_extension.node
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9 [-Wdeprecated]

**Comment by cursorial** [comment]
Try solution listed here:

https://github.com/rage8885/OpenSC2K/issues/16

**Comment by cursorial** [comment]
@xiongjy2104 Did this work?
