### ISSUE TITLE
Assets

### ISSUE THREAD

**Issue by cursorial** [rage8885/OpenSC2K#3]
We could do with creating our own assets so we avoid any issues around copyright.

**Comment by neuromancer** [comment]
We could also include a script that downloads the original assets from [archive.org](https://archive.org/details/SimCity2000_Special_Edition_Maxis-EA_Eng).

**Comment by rage8885** [comment]
I've got some preliminary code together to create tile maps from the source images, along with partially working code that can extract the original asset files. Hoping to get something pushed out within the next day or two that can pull assets from the original game files and remove the assets included here.

**Comment by kyr0** [comment]
All original assets (xpm) including sounds are included in the zip referenced here: 
https://github.com/rage8885/OpenSC2K/files/1697167/MicropolisCore.zip
