### ISSUE TITLE
Keyboard events do not work in Windows build

### ISSUE THREAD

**Issue by cdubz** [rage8885/OpenSC2K#4]
I was able to get this built on Windows, with one prerequisite - installing the `windows-build-tools` node package as described in [this SO answer](https://stackoverflow.com/questions/21658832/npm-install-error-msb3428-could-not-load-the-visual-c-component-vcbuild-ex#39235952): ``npm install --global --production windows-build-tools``

After running this, ``npm install`` does work. Unfortunately though, ``npm start`` just produces a blank (brown background) window and does not respond to any keyboard events (e.g. "o" to open a map).

**Comment by rage8885** [comment]
Thanks for the feedback - I'm working on getting a Windows VM up and running so I can do some testing there as well.

**Comment by cursorial** [comment]
I'm happy to take a look at getting it to build on Windows later on if you wanna assign this task to me?

**Comment by cdubz** [comment]
I realized I could still open the Developer Tools from the blank window and found this error -

``Exception has occurred: Error
Error: A dynamic link library (DLL) initialization routine failed.
[...] better_sqlite3.node``

This led me to [issue 36 for the better-sqlite3 library](https://github.com/JoshuaWise/better-sqlite3/issues/36) and the suggested solution there seems to work here as well: ``node_modules/.bin/electron-rebuild -f -w better-sqlite3``

After running that. ``npm start`` gets me a window and a loaded city, and keyboard events work.

So, for now anyway, there are two extra steps (3 & 5 below) for the Windows build:

1. ``git clone https://github.com/rage8885/OpenSC2K`` or download this repository
1. ``cd OpenSC2K``
1. ``npm install --global --production windows-build-tools`` (as admin)
1. ``npm install``
1. ``node_modules/.bin/electron-rebuild -f -w better-sqlite3``
1. ``npm start``

**Comment by whphhg** [comment]
This solves the Linux problem in issue #5 as well.

**Comment by vasilvestre** [comment]
Step 5 didn't solve my problem with windows 10.
