### ISSUE TITLE
Fixed typo in the readme

### ISSUE THREAD

**Issue by dherediat97** [rage8885/OpenSC2K#41]
Hello you put in the readme this
`git clone https://github.com/rage8885/OpenSC2K`

and you forget the ".git", only is that.

Greetings @dherediat97! 👍

**Comment by rage8885** [comment]
.git is not required when cloning:

❯ git clone https://github.com/rage8885/OpenSC2K
Cloning into 'OpenSC2K'...
remote: Counting objects: 2177, done.
Receiving objects:  99% (2157/2177), 11.04 MiB | 1.15 MiB/s

**Comment by dherediat97** [comment]
well, in the gith bash on windows didnt work without the extension...
