### ISSUE TITLE
Package "pngjs" refers to a non-existing file

### ISSUE THREAD

**Issue by danieldanielecki** [rage8885/OpenSC2K#54]
Can imagine that the `"pngjs": "file:C:/Users/Nicholas/Development/pngjs/",` in `package.json` has some custom modifications, but it would be good to update to certain version so we don't have errors when trying to run the repo.

**Comment by nicholas-ochoa** [comment]
I'll try and resolve this later this week (see #55)

**Comment by danieldanielecki** [comment]
@nicholas-ochoa let's continue there then, I'll close this issue.
